# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetailed1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pr1', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=20)),
                ('span1', models.CharField(max_length=20)),
                ('smallimg1', models.CharField(max_length=100)),
                ('smallimg2', models.CharField(max_length=100)),
                ('smallimg3', models.CharField(max_length=100)),
                ('dis', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Men1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menid', models.CharField(max_length=10)),
                ('mai', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=100)),
                ('span1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passwrod', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
