# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilihuiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menid', models.CharField(max_length=10)),
                ('mai', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=100)),
                ('span1', models.CharField(max_length=100)),
            ],
        ),
    ]
