# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilihuiapp', '0002_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('pr1', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=20)),
                ('span1', models.CharField(max_length=20)),
                ('smallimg1', models.CharField(max_length=100)),
                ('smallimg2', models.CharField(max_length=100)),
                ('smallimg3', models.CharField(max_length=100)),
                ('dis', models.CharField(max_length=10)),
            ],
        ),
    ]
