# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilihuiapp', '0002_lunbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mai', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=50)),
                ('p', models.CharField(max_length=50)),
                ('span', models.CharField(max_length=50)),
            ],
        ),
    ]
