# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilihuiapp', '0003_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('smalliimg1', models.CharField(max_length=50)),
                ('smalliimg2', models.CharField(max_length=50)),
                ('smalliimg3', models.CharField(max_length=50)),
                ('rmg', models.CharField(max_length=20)),
                ('rmg2', models.CharField(max_length=20)),
                ('dis', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
